### ISSUE TITLE
Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by wondertalik** [markis/vscode-code-coverage#63] opened 2021-05-03 22:51 UTC
Hello, 

Thanks for your extension. Can i use your extension for dart (flutter) code? If yes i had a problem. All details i have already explained [here](https://github.com/dart-lang/sdk/issues/42786#issuecomment-830625796).

**Comment by DanTup** [comment] 2021-05-04 09:30
I had a look in the code, and I think the issue is the use of `Number.MAX_VALUE` here:

https://github.com/markis/vscode-code-coverage/blob/bb8cdae9cb243f1514da7af2e9960f3fa87ccd56/src/extension.ts#L160

Although I'm not certain that's really a bug. VS Code seems to allow this value fine. However, it's not valid in LSP and the LSP client appears to just pass the value on as-is. I've filed an issue at https://github.com/microsoft/vscode-languageserver-node/issues/761 to see whether this is considered a bug and will be fixed there.

**Comment by DanTup** [comment] 2021-05-04 10:23
I think a better way to handle this than using `Number.MAX_VALUE` would be to change:

```
new Range(
    new Position(detail.line - 1, 0),
    new Position(detail.line - 1, Number.MAX_VALUE)
)
```

To `document.lineAt(detail.line - 1).range` instead. This will require access to the `TextDocument` for a file, but it looks like that's already available in `showStatus` (`activeTextEditor.document`) here:

https://github.com/markis/vscode-code-coverage/blob/bb8cdae9cb243f1514da7af2e9960f3fa87ccd56/src/extension.ts#L97

**Closed** 2021-10-04 13:58 UTC
